package edu.esu.kandy.slms.auth;

import edu.esu.kandy.slms.membership.MembershipType;
import edu.esu.kandy.slms.model.User;
import edu.esu.kandy.slms.service.LibraryService;

import java.util.HashMap;
import java.util.Map;

/**
 * Simple in-memory authentication service for normal library users.
 * Users log in using their generated User ID (e.g., U1004) and a password
 * provided at sign-up time.
 */
public class UserAuthService {

    private final Map<String, String> passwords = new HashMap<>();
    private final LibraryService libraryService;

    public UserAuthService(LibraryService libraryService) {
        this.libraryService = libraryService;
    }

    /**
     * Register a new library user with login credentials.
     * A User ID is auto-generated by LibraryService.
     */
    public User signUp(String name,
                       String email,
                       String contactNumber,
                       MembershipType membershipType,
                       String password) {

        User user = libraryService.createAndAddUser(name, email, contactNumber, membershipType);
        // store password keyed by the normalized (upper-case) user ID
        passwords.put(user.getId().toUpperCase(), password);
        return user;
    }

    /**
     * Attempt to log in using a (case-insensitive) user ID and password.
     * Returns the corresponding User instance on success, or null on failure.
     */
    public User login(String userIdInput, String password) {
        if (userIdInput == null || password == null) {
            return null;
        }
        String normalizedId = userIdInput.trim().toUpperCase();
        String stored = passwords.get(normalizedId);
        if (stored == null) {
            return null;
        }
        if (!stored.equals(password)) {
            return null;
        }
        return libraryService.getUser(normalizedId);
    }
}
